baseURL       = "https://chaivuriti.web.app"
languageCode  = "en-us"
title         = "Chaitanya Vuriti | Travel - Photography"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Destinations"
    url     = "destinations"
    weight  = 2
  [[menu.nav]]
    name    = "Inspiration"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Photography"
    url     = "photography"
    weight  = 4
    [[menu.nav]]
    name    = "Discover Australia"
    url     = "australia"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Chaitanya Vuriti | Travel and Photography"
  author = "Chaitanya Vuriti"
  # Google Analitycs
  googleAnalitycsID = "G-SHKQ449SEP"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://formspree.io/f/xjvdwawg"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Hi! I'm Chai"
    tagline               = "I'm working as we speak."
    primary_button        = "Plan your Trip"
    primary_button_url    = "plan-your-trip"
    secondary_button      = "Travel Guides"
    secondary_button_url  = "destinations"

  [params.destinations]
    enable    = true
    title     = "Most Popular Destinations"
    subtitle  = "Our Most Popular Travel Itineraries."

  [params.blog]
    enable    = true
    title     = "Latest from the Blog"
    subtitle  = "Find Travel Inspiration"

  [params.australia]
    enable    = true
    title     = "All about Australia"
    subtitle  = "Travel Australia like never before"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "destinations"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "address"
      phone   = "phone"
      email   = "chai@ch810ya.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Start here ↓"
        [[params.footer.sitemap.link]]
          name = "Plan your first Trip"
          url  = "plan-your-trip"
        [[params.footer.sitemap.link]]
          name = "Get Inspired"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Travel Guides"
          url  = "destinations"
        [[params.footer.sitemap.link]]
          name = "All About Australia"
          url  = "australia"
        [[params.footer.sitemap.link]]
          name = "All About Me"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Photography"
          url  = "photography"
        
        
        
      # Footer Other Channels
      [params.footer.social]
        title   = "Other Channels"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "https://medium.com/@ch810ya"
        [[params.footer.social.link]]
          name = "Substack"
          url  = "https://ch810ya.substack.com/"
        [[params.footer.social.link]]
          name = "Amazon"
          url  = "https://amazon.com/author/ch810ya"
        [[params.footer.social.link]]
          name = "500px"
          url  = "https://500px.com/p/ch810ya"
      # Footer Service
      [params.footer.service]
        title       = "We help people:"
        description = "plan, travel, experience<br>the world and create<br>fresh & brand new memories"