baseURL       = "https://chaivuriti.com"
languageCode  = "en-us"
title         = "Chai Vuriti | Travel - Photography"
summarylength = 5

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Destinations"
    url     = "destinations"
    weight  = 2
  [[menu.nav]]
    name    = "Inspiration"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Photography"
    url     = "photography"
    weight  = 4
    [[menu.nav]]
    name    = "Plan your Trip"
    url     = "plan-your-trip"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Chai Vuriti | Travel and Photography"
  author = "Chai Vuriti"
  # Google Analitycs
  googleAnalitycsID = "G-7Y77LBTX9X"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://formspree.io/f/xjvdwawg"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Enquiry Type"
    placeholder_about_the_project = "Message"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "guides"
      title  = "Travel Guides"
    [[params.contactForm.projectType]]
      value = "photos"
      title  = "Hi-Res Photos"
    [[params.contactForm.projectType]]
      value = "work"
      title  = "Work With Me"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Hi! I'm Chai"
    tagline               = "I'm working as we speak."
    primary_button        = "Plan your Trip"
    primary_button_url    = "plan-your-trip"
    secondary_button      = "Travel Guides"
    secondary_button_url  = "travel-guides"

#  [params.destinations]
#    enable    = true
#    title     = "Most Popular Destinations"
#    subtitle  = "Our Most Popular Travel Itineraries."

  [params.blog]
    enable    = true
    title     = "Latest from the Blog"
    subtitle  = "Find Travel Inspiration"

  [params.australia]
    enable    = true
    title     = "All about Australia"
    subtitle  = "Travel Australia like never before"
  
  [params.travel_guides]
    enable    = true
    title     = "Travel Guides"
    subtitle  = "Travel Australia like never before"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "destinations"
  
  [params.plan_your_trip_button]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "All Set? Plan your Trip now!"
    primary_button      = "Plan Your Trip"
    primary_button_url  = "plan-your-trip"
    secondary_button    = "Read more Guides"
    secondary_button_url = "travel-guides"

#  [params.newsletter]
#    enable              = true
#    background_image    = "images/backgrounds/cta-background.jpg"
#    title               = "Newsletter Sign Up"
#    description         = "Join our community with over 2,500+ readers to get latest travel news, updates, and great travel stories from around the world."
#    primary_button      = "Subscribe"

  [params.books]
    enable    = true
    title     = "How I Travelled Series"
    subtitle  = "Explore my Best Selling Books!"


  [params.footer]
    
    
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Start here ↓"
        [[params.footer.sitemap.link]]
          name = "Plan your first Trip"
          url  = "/plan-your-trip"
        [[params.footer.sitemap.link]]
          name = "Get Inspired"
          url  = "/blog"
        [[params.footer.sitemap.link]]
          name = "Travel Guides"
          url  = "/travel-guides"
        [[params.footer.sitemap.link]]
          name = "Free Travel Photos"
          url  = "/photography" 
      # Footer Other Links
      [params.footer.other]
        title   = "More Shortcuts ↓"
        [[params.footer.other.link]]
          name = "All About Australia"
          url  = "/australia"
        [[params.footer.other.link]]
          name = "How I Travelled Series"
          url  = "/books"
        [[params.footer.other.link]]
          name = "All Destinations"
          url  = "/destinations"
      # Footer Other Channels
      [params.footer.social]
        title   = "More Channels ↓"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "https://medium.com/@ch810ya"
        [[params.footer.social.link]]
          name = "Substack"
          url  = "https://ch810ya.substack.com/"
        [[params.footer.social.link]]
          name = "Amazon"
          url  = "https://amazon.com/author/ch810ya"
        [[params.footer.social.link]]
          name = "500px"
          url  = "https://500px.com/p/ch810ya"
      # Footer Contact Info
      [params.footer.contactInfo]
      title   = "Get in Touch"
        [[params.footer.contactInfo.link]]
          name = "About Me"
          url  = "/about"
        [[params.footer.contactInfo.link]]
          name = "Contact Us"
          url  = "/contact"
        [[params.footer.contactInfo.link]]
          name = "Newsletter"
          url  = "/about/why-subscribe"

      # Footer Service
      [params.footer.service]
        title       = "We help people:"
        description = "plan, travel, experience<br>the world and create<br>fresh & brand new memories"