baseURL       = "https://chaivuriti.web.app"
languageCode  = "en-us"
title         = "Chaitanya Vuriti | Travel - Photography"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Destinations"
    url     = "destinations"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Chaitanya Vuriti | Travel and Photography"
  author = "Chaitanya Vuriti"
  # Google Analitycs
  googleAnalitycsID = "G-SHKQ449SEP"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://formspree.io/f/xjvdwawg"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We’re a Travel Studio That Belies In the Great Ideas"
    tagline               = "WE WORK HARD, WE TRAVEL HARD"
    primary_button        = "See Our Works"
    primary_button_url    = "destinations"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.destinations]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "destinations"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "address"
      phone   = "phone"
      email   = "chai@ch810ya.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Destinations"
          url  = "destinations"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "https://medium.com/@ch810ya"
        [[params.footer.social.link]]
          name = "Substack"
          url  = "https://ch810ya.substack.com/"
        [[params.footer.social.link]]
          name = "Amazon"
          url  = "https://amazon.com/author/ch810ya"
        [[params.footer.social.link]]
          name = "500px"
          url  = "https://500px.com/p/ch810ya"
      # Footer Service
      [params.footer.service]
        title       = "We help people:"
        description = "plan, travel, experience<br>the world and create<br>fresh & brand new memories"